  backup:
    image: registry.gitlab.com/thekesolutions/tools/aspen-backup:23.6.15.0
    env_file:
        - .env
    networks:
        - net-aspen
    volumes:
        - ${ASPEN_Repo}/start.sh:/start.sh
        - ${ASPEN_Repo}/sites-enabled:/etc/apache2/sites-enabled
        - ${ASPEN_Repo}/sites-available:/etc/apache2/sites-available
        - ${ASPEN_Repo}/cron.d_bk/backup:/etc/crontabs/root
        - ${ASPEN_Repo}/log:/var/log/aspen-discovery/$SITE_sitename
        - ${ASPEN_Repo}/test.aspen.theke.io:/usr/local/aspen-discovery/sites/$SITE_sitename
        - ${ASPEN_Repo}/data:/data/aspen-discovery
        - ${ASPEN_Repo}/home:/home
        - ${ASPEN_Repo}/files:/usr/local/aspen-discovery/code/web/files
    depends_on:
      - backend
    entrypoint: ["crond", "-d", "8", "-f"]
