version: '3.7'
networks:
  net-aspen:
services:

  backend:
    image: $COMPOSE_ImagePath:$COMPOSE_ImageVersion
    ports:
      - "80:80"
    networks:
      - net-aspen
    tty: true
    volumes:
      - $COMPOSE_ClientSrvPath:/mnt
    env_file:
      - .env_backend   

  db:
    image: mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=$COMPOSE_RootPwd
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - $COMPOSE_ClientSrvPath/mariadb_data:/var/lib/mysql
    networks:
      - net-aspen

  solr:
    image: $COMPOSE_ImagePath:$COMPOSE_ImageVersion
    env_file:
      - .env_backend   
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - $COMPOSE_ClientSrvPath:/mnt
    networks:
      - net-aspen
    depends_on:
      - backend
      
  tunnel:
    image: $COMPOSE_ImagePath:$COMPOSE_ImageVersion
    env_file:
      - .env_tunnel 
    environment:
      - COMPOSE_Cron=off
      - COMPOSE_Apache=off
      - COMPOSE_Solr=off
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - $COMPOSE_ClientSrvPath:/mnt
    networks:
      - net-aspen
    entrypoint: ["/root/.ssh/tunnel.sh"]
